language: ruby
rvm:
#  - "1.8.7"
#  - "1.9.2"
  - "1.9.3"
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_install:
 # - gem update # optional, update all gems
 # - phantomjs --version # optional, output the phantomjs version
 # - gem install sqlite3
   - gem install selenium-webdriver
   - gem install rack
    

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 4
  - rackup -D
  - sleep 4

deploy:
  provider: openshift
  user: "bird_chairez@hotmail.com"
  password: "sadbuttrue12" # can be encrypted
  domain: "blogvyvs"


deploy:
  provider: cloudcontrol
  email: "bird_chairez@hotmail.com"
  password: "12345678"
  deployment: "blogvyvs/blog"